language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - CC_TEST_REPORTER_ID=c18047eab5b9de5e7e83161b517aff0c88353a00cbbf913b4713eefdf80bad3c  
before_script: 
  - phpenv config-add myconfig.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - travis_retry composer self-update
  - travis_retry composer install
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT  
after_success:
  # - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc" 
      standard: "PSR1,PSR2"
      ignore_warnings: true
  phpmd:
    enabled: true
    config:
      file_extensions: 
        - php
        - inc    
  phan:
    enabled: true
    config:
      file_extensions: "php"
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - src/test/**
        - app/src/test/**
checkout_submodules: true
  
  
  