language: php
php:
  - 7.0
  - 7.1
  
before_script: phpenv config-add myconfig.ini

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  # - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
  
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib" 
      standard: "PSR1,PSR2"
      ignore_warnings: true
      
checkout_submodules: true
  
  
  